apiVersion: v1
kind: Service
metadata:
  name: setheryops-flaskapp-svc
  labels:
    app: setheryops-flaskapp
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: setheryops-flaskapp
